# Generated by Django 5.2.1 on 2025-05-28 18:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Project name (max 100 characters)', max_length=100, validators=[django.core.validators.MinLengthValidator(1)])),
                ('description', models.TextField(blank=True, help_text='Optional project description (max 500 characters)', max_length=500)),
                ('background_color', models.CharField(choices=[('#0079bf', 'Blue'), ('#d29034', 'Orange'), ('#519839', 'Green'), ('#b04632', 'Red'), ('#89609e', 'Purple'), ('#cd5a91', 'Pink'), ('#4bbf6b', 'Light Green'), ('#00aecc', 'Light Blue'), ('#838c91', 'Gray')], default='#0079bf', help_text='Background color for the project', max_length=7)),
                ('background_image', models.URLField(blank=True, help_text='Optional background image URL', null=True)),
                ('is_private', models.BooleanField(default=True, help_text='Whether the project is private or public')),
                ('is_archived', models.BooleanField(default=False, help_text='Whether the project is archived')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='Project owner who created it', on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('admin', 'Admin')], default='editor', help_text="User's role in the project", max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(blank=True, help_text='User who invited this member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_memberships', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='The project', on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('user', models.ForeignKey(help_text='The user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Membership',
                'verbose_name_plural': 'Project Memberships',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Users who have access to this project', related_name='projects', through='projects.ProjectMembership', through_fields=('project', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='projectmembership',
            index=models.Index(fields=['project', 'user'], name='projects_pr_project_710ab3_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmembership',
            index=models.Index(fields=['role'], name='projects_pr_role_fde63d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectmembership',
            unique_together={('project', 'user')},
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner'], name='projects_pr_owner_i_dea3a1_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_at'], name='projects_pr_created_6b02e3_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_private'], name='projects_pr_is_priv_aaa3f3_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_archived'], name='projects_pr_is_arch_0a4024_idx'),
        ),
    ]
